// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/matches.ts";
import * as $1 from "./routes/api/tables.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/matches/[id].tsx";
import * as $$0 from "./islands/OpenMatches.tsx";

const manifest = {
  routes: {
    "./routes/api/matches.ts": $0,
    "./routes/api/tables.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/matches/[id].tsx": $3,
  },
  islands: {
    "./islands/OpenMatches.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
